# Basic Information
title: Sarah Allen
position: Head of Research, <a href="https://www.flashbots.net/" rel="noopener"><autocolor>Flashbots</autocolor></a>
affiliation: Research Program Manager, IC3
affiliation_link: https://www.initc3.org/
email: sarahallen@cornell.edu

# Search Engine Optimization (SEO)
keywords: Sarah Allen, Flashbots, IC3, MEV, mechanism design, blockchain, AI, cryptography
description: Sarah Allen — Head of Research at Flashbots and Research Program Manager at IC3. Research on MEV, mechanism design, cryptography, and blockchain x AI.
canonical: https://sarahalle.github.io/

# Links
google_scholar: https://scholar.google.com/citations?user=hRsmFmwAAAAJ
github_link: https://github.com/sarahalle
linkedin: https://www.linkedin.com/in/1sarahallen/
twitter: https://x.com/sarahalle_

# Images
avatar: ./assets/img/avatar.png
favicon: ./assets/img/avatar.png
favicon_dark: ./assets/img/avatar.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Serif" # or "Sans Serif"
